<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>OldMarket.Bootstrap</AssemblyName>
    <Version>0.1.0</Version>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputPath>bin/Bootstrap/$(Configuration)/</OutputPath>
  </PropertyGroup>
  <ItemGroup><Compile Include="Bootstrap.cs" /></ItemGroup>
</Project>
