<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><Compile Remove="ContractChecks.cs"/><Compile Include="../MapManifestReader.cs" Link="MapManifestReader.cs"/><Compile Include="../PoiLabelLayout.cs" Link="PoiLabelLayout.cs"/><Compile Include="../MapArea.cs" Link="MapArea.cs"/><Compile Include="../MapPoi.cs" Link="MapPoi.cs"/><Compile Include="../MapWheelZoom.cs" Link="MapWheelZoom.cs"/><Compile Include="../MinimapZoom.cs" Link="MinimapZoom.cs"/><Compile Include="../MapViewportGeometry.cs" Link="MapViewportGeometry.cs"/><Compile Include="../NavMath.cs" Link="NavMath.cs"/><Compile Include="../MarkerStore.cs" Link="MarkerStore.cs"/><Compile Include="../Texts.cs" Link="Texts.cs"/><Compile Include="../NavigationLayout.cs" Link="NavigationLayout.cs"/><Compile Include="../ExpansionRules.cs" Link="ExpansionRules.cs"/><Compile Include="../HudPlacement.cs" Link="HudPlacement.cs"/></ItemGroup></Project>
